from __future__ import annotations

from app.workshops.contracts import Workshop, WorkshopAction

WORKSHOP = Workshop(
    area='governance',
    purpose='JakoĹ›Ä‡ pamiÄ™ci, kolejki, SLA, ownerzy i alerty.',
    min_profile='clean_operator',
    risk='medium',
    recommended_first_action='quality_alerts',
    actions=(
        WorkshopAction(
            action='quality_alerts',
            tool_name='get_quality_alerts',
            purpose='PokaĹĽ alerty jakoĹ›ci.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'validated_before': 'str|null',
 'as_of': 'str|null',
 'scope_code': 'str|null',
 'project_key': 'str|null',
 'layer_code': 'str|null',
 'area_code': 'str|null',
 'memory_type': 'str|null',
 'tag': 'str|null',
 'text_query': 'str|null'},
        ),
        WorkshopAction(
            action='operations_dashboard',
            tool_name='get_mapi_operations_observability',
            purpose='Bounded read-only runtime, transport, graph, embedding, retrieval and provider dashboard.',
            min_profile='clean_operator',
            risk='low',
            risk_class='R0',
            payload_schema={
                'project_key': 'str|null',
                'timeout_budget_ms': 'int',
                'include_debug': 'bool',
            },
        ),
        WorkshopAction(
            action='canonical_truth_review',
            tool_name='get_canonical_truth_review',
            purpose='Read-only evidence and consumer-impact review for active legacy truth relations.',
            min_profile='reader',
            risk='low',
            risk_class='R0',
            payload_schema={'project_key': 'str|null', 'include_items': 'bool', 'sample_limit': 'int'},
        ),
        WorkshopAction(
            action='legacy_graph_audit',
            tool_name='get_legacy_graph_audit',
            purpose='Read-only classification of trusted, invalid, redundant and legacy-unverified graph edges.',
            min_profile='reader',
            risk='low',
            risk_class='R0',
            payload_schema={
                'project_key': 'str|null',
                'include_trusted': 'bool',
                'include_candidates': 'bool',
                'sample_limit': 'int',
            },
        ),
        WorkshopAction(
            action='queue_dashboard',
            tool_name='get_operational_queue_dashboard',
            purpose='Dashboard kolejki operacyjnej.',
            min_profile='clean_operator',
            risk='low',
            payload_schema=None,
        ),
        WorkshopAction(
            action='owner_workload',
            tool_name='get_effective_owner_workload',
            purpose='ObciÄ…ĹĽenie wĹ‚aĹ›cicieli.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'limit': 'int', 'validated_before': 'str|null', 'as_of': 'str|null',
 'scope_code': 'str|null', 'project_key': 'str|null', 'layer_code': 'str|null',
 'area_code': 'str|null', 'memory_type': 'str|null', 'tag': 'str|null',
 'text_query': 'str|null', 'effective_owner_key': 'str|null',
 'effective_owner_type': 'str|null'},
        ),
        WorkshopAction(
            action='scope_mismatches',
            tool_name='list_project_scope_mismatches',
            purpose='Global/default scope w project memories.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'project_key': 'str|null', 'limit': 'int'},
        ),
        WorkshopAction(
            action='hygiene_inventory',
            tool_name='get_memory_hygiene_inventory',
            purpose='Read-only inventory owner/scope/importance/revalidation hygiene.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'project_key': 'str', 'as_of': 'str|null', 'include_candidates': 'bool'},
        ),
        WorkshopAction(
            action='hygiene_preview',
            tool_name='preview_memory_hygiene',
            purpose='Deterministic metadata-only hygiene preview with fingerprints.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'project_key': 'str', 'as_of': 'str|null'},
        ),
        WorkshopAction(
            action='hygiene_apply',
            tool_name='apply_memory_hygiene',
            purpose='Apply exact approved hygiene preview after verified backup.',
            min_profile='admin',
            risk='high',
            payload_schema={'project_key': 'str', 'expected_preview_hash': 'str', 'applied_by': 'str',
 'reason': 'str', 'backup_path': 'str', 'confirm_metadata_repair': 'bool', 'as_of': 'str|null'},
        ),
        WorkshopAction(
            action='hygiene_run',
            tool_name='get_memory_hygiene_run',
            purpose='Inspect one hygiene apply/rollback run.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'run_id': 'int'},
        ),
        WorkshopAction(
            action='hygiene_rollback_preview',
            tool_name='preview_memory_hygiene_rollback',
            purpose='Preview exact metadata rollback for a completed hygiene run.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'run_id': 'int'},
        ),
        WorkshopAction(
            action='hygiene_rollback',
            tool_name='rollback_memory_hygiene_run',
            purpose='Execute exact guarded hygiene rollback.',
            min_profile='admin',
            risk='high',
            payload_schema={'run_id': 'int', 'expected_rollback_preview_hash': 'str',
 'rolled_back_by': 'str', 'notes': 'str|null'},
        ),
        WorkshopAction(
            action='transport_status',
            tool_name='get_mcp_transport_status',
            purpose='Read-only HTTP backpressure and keepalive contract with runtime counters.',
            min_profile='reader',
            risk='low',
            payload_schema={},
        ),
        WorkshopAction(
            action='runtime_readiness',
            tool_name='get_runtime_readiness',
            purpose='Read-only proof of active runtime identity and freshness.',
            min_profile='reader',
            risk='low',
            payload_schema={'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='private_runtime',
            tool_name='get_private_runtime_status',
            purpose='Read-only status prywatnego single-user runtime i efektywnych flag multiuser.',
            min_profile='reader',
            risk='low',
            payload_schema={'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='provider_observability',
            tool_name='get_sandman_provider_observability',
            purpose='Read-only content-free provider and model queue observability.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'project_key': 'str|null', 'limit': 'int', 'include_debug': 'bool'},
        ),
    ),
    guardrails=(),
)
