from __future__ import annotations

from pathlib import Path
from typing import Any


SEED_MARKER = "mapi-demo-seed-v1"


def seed_demo_database(path: Path) -> dict[str, Any]:
    """Create deterministic fictional demo records without external providers."""
    from app.runtime.context import configure_runtime_context

    configure_runtime_context(
        root=path.parent.parent,
        data_dir=path.parent,
        db_path=path,
    )

    import server_core
    from app import timeline

    connection = server_core.get_db_connection()
    try:
        existing = connection.execute(
            "SELECT id FROM memories WHERE source_event_ref = ? ORDER BY id",
            (SEED_MARKER,),
        ).fetchall()
        if existing:
            return {
                "status": "already_seeded",
                "database": str(path),
                "memory_ids": [int(row["id"]) for row in existing],
            }

        records = [
            {
                "project_key": "demo-project",
                "summary_short": "Use explicit previews before lifecycle changes",
                "content": "The demo agent previews lifecycle changes before any guarded apply.",
                "memory_type": "decision",
                "tags": "demo,safety,lifecycle",
            },
            {
                "project_key": "demo-project",
                "summary_short": "Store provenance with durable memories",
                "content": "Every durable demo memory records a fictional source and project.",
                "memory_type": "project_rule",
                "tags": "demo,provenance",
            },
            {
                "project_key": "sample-research",
                "summary_short": "The prototype uses a local SQLite database",
                "content": "The fictional research prototype keeps its test data in local SQLite.",
                "memory_type": "project_fact",
                "tags": "demo,sqlite,research",
            },
            {
                "project_key": "sample-research",
                "summary_short": "Prototype storage decision",
                "content": "The fictional prototype initially considered an in-memory store.",
                "memory_type": "decision",
                "tags": "demo,superseded",
            },
            {
                "project_key": "sample-research",
                "summary_short": "Prototype storage decision",
                "content": "The fictional prototype now uses SQLite for durable local storage.",
                "memory_type": "decision",
                "tags": "demo,current",
            },
            {
                "project_key": "demo-project",
                "summary_short": "Demo review cadence",
                "content": "The fictional team reviews low-confidence notes every Friday.",
                "memory_type": "project_rule",
                "tags": "demo,conflict,review",
            },
            {
                "project_key": "demo-project",
                "summary_short": "Demo review cadence",
                "content": "The fictional team reviews low-confidence notes every Monday.",
                "memory_type": "project_rule",
                "tags": "demo,conflict,review",
            },
        ]

        created: list[dict[str, Any]] = []
        for item in records:
            created.append(
                server_core._insert_memory(
                    connection,
                    **item,
                    source="synthetic-demo",
                    source_context="generated by mapi-seed-demo",
                    source_event_ref=SEED_MARKER,
                    confidence_score=0.9,
                    importance_score=0.6,
                    scope_code="project",
                    ensure_embedding=False,
                )
            )

        first_id = int(created[0]["id"])
        second_id = int(created[1]["id"])
        old_id = int(created[3]["id"])
        new_id = int(created[4]["id"])
        server_core._create_link(
            connection,
            first_id,
            second_id,
            "supports",
            0.9,
            "synthetic-demo",
            operation_id=SEED_MARKER,
        )
        connection.execute(
            "UPDATE memories SET superseded_by_memory_id = ?, activity_state = 'superseded' WHERE id = ?",
            (new_id, old_id),
        )
        connection.execute(
            "UPDATE memories SET supersedes_memory_id = ? WHERE id = ?",
            (old_id, new_id),
        )
        timeline.record_project_event(
            connection,
            project_key="demo-project",
            event_type="project.milestone_recorded",
            title="Synthetic demo data created",
            description="Deterministic fictional records for the public quickstart.",
            origin="system",
            memory_ids=[int(item["id"]) for item in created],
            tags=["demo", "synthetic"],
            operation_id=SEED_MARKER,
        )
        connection.commit()
        return {
            "status": "seeded",
            "database": str(path),
            "memory_ids": [int(item["id"]) for item in created],
            "projects": ["demo-project", "sample-research"],
            "links": 1,
            "supersession_examples": 1,
            "conflict_examples": 1,
            "timeline_events": 1,
        }
    finally:
        connection.close()
