from __future__ import annotations

from app.workshops.contracts import Workshop, WorkshopAction

WORKSHOP = Workshop(
    area="sandman",
    purpose="Kanoniczny proposal-only Sandman: deterministic core, Gemini shadow, jeden scheduler i jeden ledger.",
    min_profile="agent",
    risk="medium",
    recommended_first_action="canonical_status",
    actions=(
        WorkshopAction(
            action="canonical_status",
            tool_name="get_sandman_canonical_status",
            purpose="Stan jedynego schedulera, provider path, flag i oczekiwanego nocnego runu.",
            min_profile="agent",
            risk="low",
            payload_schema={"project_key": "str", "include_debug": "bool"},
        ),
        WorkshopAction(
            action="canonical_preview",
            tool_name="preview_sandman_canonical",
            purpose="Read-only preview deterministic core i stateless Gemini shadow bez network call i bez zapisów.",
            min_profile="agent",
            risk="low",
            payload_schema={
                "project_key": "str",
                "scope_code": "str",
                "candidate_limit": "int",
                "proposal_budget": "int",
                "memory_ids_json": "str|null",
                "allowed_actions_json": "str|null",
                "include_debug": "bool",
            },
        ),
        WorkshopAction(
            action="canonical_runs",
            tool_name="list_sandman_canonical_runs",
            purpose="Lista jednego kanonicznego ledgeru schedulera.",
            min_profile="agent",
            risk="low",
            payload_schema={
                "run_type": "str|null",
                "status": "str|null",
                "project_key": "str|null",
                "limit": "int",
            },
        ),
        WorkshopAction(
            action="canonical_run",
            tool_name="get_sandman_canonical_run",
            purpose="Szczegóły jednego kanonicznego runu.",
            min_profile="agent",
            risk="low",
            payload_schema={"run_id": "int"},
        ),
        WorkshopAction(
            action="provider_status",
            tool_name="get_sandman_provider_v3_status",
            purpose="Read-only provider registry, redaction contract i model state.",
            min_profile="agent",
            risk="low",
            payload_schema={"project_key": "str|null", "scope_code": "str|null"},
        ),
        WorkshopAction(
            action="provider_request_preview",
            tool_name="preview_sandman_provider_request",
            purpose="Zbuduj lokalnie zredagowany provider request z jawnych ID.",
            min_profile="agent",
            risk="low",
            payload_schema={
                "project_key": "str",
                "scope_code": "str",
                "memory_ids_json": "str",
                "allowed_actions_json": "str",
                "provider_name": "str",
                "proposal_budget": "int",
                "include_debug": "bool",
            },
        ),
        WorkshopAction(
            action="provider_deterministic_preview",
            tool_name="preview_sandman_provider_deterministic",
            purpose="Read-only deterministic provider preview z pełną walidacją odpowiedzi.",
            min_profile="agent",
            risk="low",
            payload_schema={
                "project_key": "str",
                "scope_code": "str",
                "memory_ids_json": "str",
                "allowed_actions_json": "str",
                "provider_name": "str",
                "proposal_budget": "int",
                "include_debug": "bool",
            },
        ),
        WorkshopAction(
            action="semantic_shadow_preview",
            tool_name="preview_sandman_gemini_shadow",
            purpose="Preview stateless Gemini shadow bez network call.",
            min_profile="agent",
            risk="low",
            payload_schema={
                "project_key": "str",
                "scope_code": "str",
                "memory_ids_json": "str",
                "allowed_actions_json": "str",
                "proposal_budget": "int",
                "model_role": "str",
                "include_debug": "bool",
            },
        ),
        WorkshopAction(
            action="semantic_shadow_run",
            tool_name="run_sandman_gemini_shadow",
            purpose="Audytowany, stateless Gemini shadow. Zapisuje wyłącznie metadane runu, nigdy memory ani queue.",
            min_profile="maintainer",
            risk="medium",
            payload_schema={
                "project_key": "str",
                "scope_code": "str",
                "memory_ids_json": "str",
                "allowed_actions_json": "str",
                "requested_by": "str",
                "proposal_budget": "int",
                "model_role": "str",
                "include_debug": "bool",
                "notes": "str|null",
            },
        ),
        WorkshopAction(
            action="semantic_shadow_list",
            tool_name="list_sandman_gemini_shadow_runs",
            purpose="Lista bezpiecznych metadanych Gemini shadow.",
            min_profile="agent",
            risk="low",
            payload_schema={
                "status": "str|null",
                "project_key": "str|null",
                "model_name": "str|null",
                "validation_status": "str|null",
                "limit": "int",
            },
        ),
        WorkshopAction(
            action="semantic_shadow_get",
            tool_name="get_sandman_gemini_shadow_run",
            purpose="Bezpieczne metadane jednego Gemini shadow runu.",
            min_profile="agent",
            risk="low",
            payload_schema={"run_id": "int"},
        ),
        WorkshopAction(
            action="semantic_evaluation_corpus",
            tool_name="get_sandman_semantic_evaluation_corpus",
            purpose="Manifest syntetycznego corpus do oceny providerów.",
            min_profile="agent",
            risk="low",
            payload_schema={"include_case_ids": "bool", "include_debug": "bool"},
        ),
        WorkshopAction(
            action="semantic_evaluation",
            tool_name="evaluate_sandman_semantic_provider",
            purpose="Ocena deterministic baseline lub dostarczonego replay bez mutacji.",
            min_profile="agent",
            risk="low",
            payload_schema={
                "evaluation_kind": "str",
                "prediction_bundle_json": "str|null",
                "include_case_results": "bool",
                "include_debug": "bool",
            },
        ),
    ),
    guardrails=(
        "Jeden scheduler i jeden ledger.",
        "Model działa wyłącznie jako shadow/proposal-only.",
        "Brak auto-apply, destructive runów i lokalnej Gemmy w aktywnej powierzchni.",
    ),
)
