from __future__ import annotations

from app.workshops.contracts import Workshop, WorkshopAction

WORKSHOP = Workshop(
    area='gemma',
    purpose='Gemma Worker przez LM Studio/LMS jako lokalna warstwa wykonawcza Jagody.',
    min_profile='clean_operator',
    risk='medium',
    recommended_first_action='create_job',
    actions=(
        WorkshopAction(
            action='worker_status',
            tool_name='gemma_worker_status',
            purpose='Sprawdz kontrakt i status Gemma Worker.',
            min_profile='clean_operator',
            risk='low',
            payload_schema=None,
        ),
        WorkshopAction(
            action='create_job',
            tool_name='gemma_worker_create_job',
            purpose='Utworz etapowy job Gemma Worker.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'task': 'str',
 'repo': 'str',
 'project_key': 'str|null',
 'context': 'str|null',
 'allowed_actions_json': 'str|null',
 'acceptance_criteria_json': 'str|null'},
        ),
        WorkshopAction(
            action='get_job',
            tool_name='gemma_worker_get_job',
            purpose='Pobierz zapisany job Gemma Worker.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'job_id': 'int'},
        ),
        WorkshopAction(
            action='prepare_plan',
            tool_name='gemma_worker_prepare_plan',
            purpose='Przygotuj plan dla joba Gemma Worker bez zmian w plikach.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'job_id': 'int',
 'max_tokens': 'int|null',
 'timeout_seconds': 'int|null',
 'ensure_loaded': 'bool',
 'unload_after_call': 'bool|null'},
        ),
        WorkshopAction(
            action='approve_job',
            tool_name='gemma_worker_approve_job',
            purpose='Zatwierdz job Gemma Worker do wykonania.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'job_id': 'int'},
        ),
        WorkshopAction(
            action='reject_job',
            tool_name='gemma_worker_reject_job',
            purpose='Odrzuc job lub plan Gemma Worker.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'job_id': 'int', 'reason': 'str|null'},
        ),
        WorkshopAction(
            action='cancel_job',
            tool_name='gemma_worker_cancel_job',
            purpose='Anuluj job Gemma Worker przed wykonaniem.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'job_id': 'int', 'reason': 'str|null'},
        ),
        WorkshopAction(
            action='run_job',
            tool_name='gemma_worker_run_job',
            purpose='Uruchom zatwierdzony job Gemma Worker.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'job_id': 'int',
 'max_tokens': 'int|null',
 'timeout_seconds': 'int|null',
 'ensure_loaded': 'bool',
 'unload_after_call': 'bool|null'},
        ),
        WorkshopAction(
            action='get_report',
            tool_name='gemma_worker_get_report',
            purpose='Pobierz raport zapisany dla joba Gemma Worker.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'job_id': 'int'},
        ),
        WorkshopAction(
            action='run_task',
            tool_name='gemma_worker_run_task',
            purpose='Uruchom task Gemma Worker.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'task': 'str',
 'repo': 'str',
 'allowed_actions_json': 'str|null',
 'acceptance_criteria_json': 'str|null',
 'context': 'str|null',
 'max_tokens': 'int|null',
 'timeout_seconds': 'int|null',
 'ensure_loaded': 'bool',
 'unload_after_call': 'bool|null'},
        ),
        WorkshopAction(
            action='prepare_task',
            tool_name='gemma_worker_prepare_task',
            purpose='Przygotuj i zwaliduj zadanie dla Gemma Worker.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'task': 'str',
 'repo': 'str',
 'allowed_actions_json': 'str|null',
 'acceptance_criteria_json': 'str|null',
 'context': 'str|null'},
        ),
        WorkshopAction(
            action='report',
            tool_name='gemma_worker_report',
            purpose='Zwaliduj raport wykonania Gemma Worker przed review Jagody.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'status': 'str',
 'summary': 'str',
 'changed_files_json': 'str|null',
 'actions_used_json': 'str|null',
 'tests_run_json': 'str|null',
 'needs_agent_review': 'bool'},
        ),
        WorkshopAction(
            action='status',
            tool_name='gemma_lms_status',
            purpose='Sprawdz konfiguracje i rezydentnosc Gemmy/LMS.',
            min_profile='clean_operator',
            risk='low',
            payload_schema=None,
        ),
        WorkshopAction(
            action='load',
            tool_name='gemma_lms_load',
            purpose='Zaladuj Gemme przez `lms load`.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema=None,
        ),
        WorkshopAction(
            action='unload',
            tool_name='gemma_lms_unload',
            purpose='Wyladuj Gemme przez `lms unload`.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema=None,
        ),
        WorkshopAction(
            action='ask',
            tool_name='gemma_ask',
            purpose='Zadaj Gemmie zadanie lub pytanie robocze.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'prompt': 'str',
 'system_prompt': 'str|null',
 'max_tokens': 'int|null',
 'timeout_seconds': 'int|null',
 'ensure_loaded': 'bool',
 'unload_after_call': 'bool|null'},
        ),
        WorkshopAction(
            action='coding_task',
            tool_name='gemma_coding_task',
            purpose='Popros Gemma Worker o strukturalna analize lub przygotowanie zadania.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'task': 'str',
 'context': 'str|null',
 'repository_hint': 'str|null',
 'max_tokens': 'int|null',
 'timeout_seconds': 'int|null',
 'ensure_loaded': 'bool',
 'unload_after_call': 'bool|null'},
        ),
    ),
    guardrails=('Gemma Worker wykonuje lokalne zadania w ramach polityki MAPI. MAPI nadzoruje i recenzuje raport.',),
)
